include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
 - build
 - package
 - test-package

variables:
  DEPS: build-essential

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y build-dep .
  - apt-get -y install $DEPS

.tags: &tags
  tags:
    - librem5

build:native:buster:
  <<: *tags
  stage: build
  image: debian:buster
  artifacts:
    paths:
      - _build
  script:
    - meson --werror . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

build:native:bullseye:
  <<: *tags
  stage: build
  image: debian:bullseye
  artifacts:
    paths:
      - _build
  script:
    - meson --werror . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

package:deb-debian-buster:
  extends: .l5-build-debian-package

package:deb-debian-buster:arm64:
  tags:
    - librem5:arm64
  before_script: []
  extends: .l5-build-debian-package

package:deb-debian-bullseye:arm64:
  tags:
    - librem5:arm64
  variables:
    L5_DOCKER_IMAGE: debian:bullseye
    L5_ADD_SCRATCH_CI: 'false'
  before_script: []
  extends: .l5-build-debian-package

autopkgtest-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-autopkgtest-debian-package

lintian-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-lintian-debian-package

